### ISSUE TITLE
Fail to build on NixOS due to gnome-bluetooth

### ISSUE THREAD

**Issue by Nocxium** [Jas-SinghFSU/HyprPanel#291]
When i try to build, i get the following error:
`evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "gnome-bluetooth" at /nix/store/3p6803sfb55m8xcdcsx2alayfqf6nphs-source/nix/default.nix:24'`

**Comment by Piecuuu** [comment]
this panel drives me nuts more and more but now i can't even rebuild my system without pinning the frickin flake

**Comment by anotherhadi** [comment]
> this panel drives me nuts more and more but now i can't even rebuild my system without pinning the frickin flake

What's your nix version?

**Comment by Piecuuu** [comment]
> What's your nix version?

NixOS 24.05

**Comment by anotherhadi** [comment]
> > What's your nix version?
> 
> 
> 
> NixOS 24.05, Lix 2.91.0

Did you add a nixpkgs.follow in the hyprpanel flake call?

**Comment by Nocxium** [comment]
> Did you add a nixpkgs.follow in the hyprpanel flake call?

Not the one you asked the question to, but yes I have this in my flake.nix, and still get the error:

```
    hyprpanel = {
      url = "github:Jas-SinghFSU/HyprPanel";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

**Comment by anotherhadi** [comment]
> > Did you add a nixpkgs.follow in the hyprpanel flake call?
> 
> 
> 
> Not the one you asked the question to, but yes I have this in my flake.nix, and still get the error:
> 
> 
> 
> ```
> 
>     hyprpanel = {
> 
>       url = "github:Jas-SinghFSU/HyprPanel";
> 
>       inputs.nixpkgs.follows = "nixpkgs";
> 
>     };
> 
> ```
> 
> 

Try to remove it and rebuild

**Comment by Nocxium** [comment]
> Try to remove it and rebuild

Doesnt make any difference :/ Still the same error

**Comment by orxngc** [comment]
i'll try to fix this today fellow nerds

**Comment by orxngc** [comment]
that should fix the issue. if it doesn't, please mention me again, preferably on discord

**Comment by Piecuuu** [comment]
@orxngc I'm still experiencing this error. This issue should be reopened.

**Comment by orxngc** [comment]
i will look into this again tomorrow then

**Comment by orxngc** [comment]
it really should be fixed now

**Comment by Ysujy** [comment]
The error is still present on my end after [83d2aa6](https://github.com/Jas-SinghFSU/HyprPanel/commit/83d2aa64400dba87ed7dbcd52ee06c832900dce2) :/

**Comment by TimofeyAxenov** [comment]
@orxngc Still there. Doesn't work either if I use the follows line or not

**Comment by M0NsTeRRR** [comment]
New user, I just installed and got the same issue, I guess it's not fixed yet.

**Comment by orxngc** [comment]
@M0NsTeRRR please tell me if running `nix run` in the folder works

**Comment by M0NsTeRRR** [comment]
I've created a PR that worked for my config (I don't have anymore the error linked above)

**Comment by M0NsTeRRR** [comment]
Can some of you test my PR and see if it fixes for you (just use my repo instead)

**Comment by zDyanTB** [comment]
> Can some of you test my PR and see if it fixes for you (just use my repo instead)

Fixed

**Comment by M0NsTeRRR** [comment]
Yeah okay so the actual flake only work for unstable and not for stable. As I'm not a nix expert I don't know how to manage it :/

**Comment by raininja** [comment]
the Question is: can aylurs-gtk-shell build without the gnome-bluetooth dependency, because that's a hard no for me, due to the systemd dependency. Investigating.

**Comment by kashw2** [comment]
Just to dot some I's and cross some T's. Everyone here who has removed `inputs.nixpkgs.follows = "nixpkgs"` from their hyprpanel input has also then updated their flake.lock and run a rebuild without cache and the `--refresh` flag (if just using `nix build`)

**Comment by Piecuuu** [comment]
First of all, the mere inclusion of the nixpkgs overlay, makes it unable to build on 24.05, due to
```
error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "gnome-bluetooth" at /nix/store/zknqfdygdbl1fa6swpv9qnknfxgqkn2a-source/nix/default.nix:24'
```
([My flake here, private git server](https://git.piecuu.pl/Piecuu/nixos-flake/commit/4faef614b13b217b5086ce3805a9449ad63a620d))

Second of all, I personally think we should wait until 24.11 drops. I have estimated for 24.11 to release in about a month due to the fact, that, previously, 23.11 has released at the end of November. Anyways, this is all up to the maintainers, if fix or wait, of course.
