### ISSUE TITLE
Hash mismatch home-manager nix

### ISSUE THREAD

**Issue by delegadissim** [Jas-SinghFSU/HyprPanel#479]
**Describe the bug**
error: hash mismatch in fixed-output derivation '/nix/store/1nn8yqkcgds1frzkh4hxhbk3d0ifv2wd-source.drv':
         specified: sha256-SN4m0ka5VHLIQYTszhlCIB+2D+nyWMzJM5n5bZdkG/I=
            got:    sha256-l623fIVhVCU/ylbBmohAtQNbK0YrWlEny0sC/vBJ+dU=
error: 1 dependencies of derivation '/nix/store/ksbmi4ar7nzjd88zgq4py9a7kx9bkz27-matugen-2.4.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lddppxni1jn62zrr55v1hn5sjs3j61jm-hyprpanel.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8pb5lm53y24r9vpcxhv7mqsqsb3z1rw1-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/hrwsb368vhs6vscsgb85q9hqpf3pkf23-home-manager-generation.drv' failed to build

**To Reproduce**
just need to nix flake update
then home-manager switch and it will happen
**Expected behavior**
The hash is not the same

**Screenshots**

**Desktop:**
 - Distribution: Nixos (but everyone with home-manager should be able to reproduce it)
 - Window Manager/Desktop Environment: Hyprland

**Comment by anotherhadi** [comment]
Fixed in https://github.com/NixOS/nixpkgs/issues/355078
Not related to Hyprpanel itself

**Comment by JackMechem** [comment]
I'm also having the same issue. I'm on nixos-unstable, is there something I need to do? 

I ran `sudo nix-channel --update` and `sudo nixos-rebuild switch --flake /etc/nixos/#nixos` and get the same error with is before it:
```
evaluation warning: The ‘gnome.gnome-bluetooth’ was moved to top-level. Please use ‘pkgs.gnome-bluetooth’ directly.
```

**Comment by hambosto** [comment]
already flake update and did rebuild, but hash mismatch still appear

❯ nix flake update

❯ nixos-rebuild switch --flake .
building the system configuration...
evaluation warning: The ‘gnome.gnome-bluetooth’ was moved to top-level. Please use ‘pkgs.gnome-bluetooth’ directly.
error: hash mismatch in fixed-output derivation '/nix/store/1nn8yqkcgds1frzkh4hxhbk3d0ifv2wd-source.drv':
         specified: sha256-SN4m0ka5VHLIQYTszhlCIB+2D+nyWMzJM5n5bZdkG/I=
            got:    sha256-l623fIVhVCU/ylbBmohAtQNbK0YrWlEny0sC/vBJ+dU=
error: 1 dependencies of derivation '/nix/store/ksbmi4ar7nzjd88zgq4py9a7kx9bkz27-matugen-2.4.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lddppxni1jn62zrr55v1hn5sjs3j61jm-hyprpanel.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vl2rjx2nn3hwc04h4kd7gq3zh1609rhx-hm_hyprhyprland.conf.drv' failed to build
error: 1 dependencies of derivation '/nix/store/gj8311cccg1l3d374bm2j8j290zgrl4b-home-manager-path.drv' failed to build

**Comment by anotherhadi** [comment]
> ```
> evaluation warning: The ‘gnome.gnome-bluetooth’ was moved to top-level. Please use ‘pkgs.gnome-bluetooth’ directly.
> ```
That's something else that is in another issue, just a warning and do not prevent rebuilding.
We should just wait for the new matugen package to be merged in the nixpkgs unstable branch, 1 or 2 days ig

**Comment by md-salehzadeh** [comment]
if you don't want to wait for the matugen package to be updated you can fix it manually

```nix
{
  nixpkgs.overlays = [
    (final: prev: {
      matugen = final.rustPlatform.buildRustPackage rec {
        pname = "matugen";
        version = "2.4.0";

        src = final.fetchFromGitHub {
          owner = "InioX";
          repo = "matugen";
          rev = "refs/tags/v${version}";
          hash = "sha256-l623fIVhVCU/ylbBmohAtQNbK0YrWlEny0sC/vBJ+dU=";
        };

        cargoHash = "sha256-FwQhhwlldDskDzmIOxhwRuUv8NxXCxd3ZmOwqcuWz64=";

        meta = {
          description = "Material you color generation tool";
          homepage = "https://github.com/InioX/matugen";
          changelog = "https://github.com/InioX/matugen/blob/${src.rev}/CHANGELOG.md";
          license = final.lib.licenses.gpl2Only;
          maintainers = with final.lib.maintainers; [ lampros ];
          mainProgram = "matugen";
        };
      };
    })
  ];
}
```
